/**
 * OpenCode hook definitions.
 *
 * OpenCode hooks are TypeScript plugins installed to ~/.config/opencode/plugins/.
 * They export a Plugin object with hooks keyed by event name.
 *
 * Limitations vs Claude Code:
 * - `tool.execute.before` can modify args but CANNOT block tool calls.
 * - No true blocking mechanism (permission.ask is too coarse).
 *
 * Strategy: "soft interception + reminder injection"
 * 1. tool.execute.before — detect boundary violations, replace args to neutralize
 *    the operation (e.g., prepend echo to bash commands, empty write content)
 *    and inject a warning message.
 * 2. experimental.chat.messages.transform — read Harmonia data files, inject
 *    reminders about dispatch timeouts, idle phases, pending reviews.
 *
 * Both hooks are generated as a single plugin file.
 */

import { defineHooks } from '@s_s/agent-kit';
import type { HookParams } from './content.js';
import {
    BLOCKED_COMMANDS,
    CODE_EXTENSIONS,
    DISPATCH_TIMEOUT_MINUTES,
    PHASE_IDLE_TIMEOUT_MINUTES,
    REVIEW_PENDING_TIMEOUT_MINUTES,
} from './content.js';

/**
 * Generate the OpenCode plugin TypeScript source code.
 *
 * This produces a single plugin file that handles both:
 * - tool.execute.before: soft boundary interception
 * - experimental.chat.messages.transform: proactive reminders
 */
function generateOpenCodePlugin(params: HookParams): string {
    const codeExtsJson = JSON.stringify(CODE_EXTENSIONS);
    const blockedCmdsJson = JSON.stringify(BLOCKED_COMMANDS);

    // We generate raw TS source as a string. All values from params/constants
    // are baked in as literals at generation time.
    return `import type { Plugin } from 'opencode';
import { readFileSync } from 'fs';
import { resolve } from 'path';

// ── Baked-in constants (generated by Harmonia setup) ──
const PROJECT_DIR = ${JSON.stringify(params.projectDir)};
const DATA_DIR = ${JSON.stringify(params.dataDir)};
const PROJECT_NAME = ${JSON.stringify(params.projectName)};
const PROJECT_DATA = resolve(DATA_DIR, PROJECT_NAME);

const CODE_EXTENSIONS: readonly string[] = ${codeExtsJson};
const BLOCKED_COMMANDS: readonly string[] = ${blockedCmdsJson};
const DISPATCH_TIMEOUT_MINUTES = ${DISPATCH_TIMEOUT_MINUTES};
const PHASE_IDLE_TIMEOUT_MINUTES = ${PHASE_IDLE_TIMEOUT_MINUTES};
const REVIEW_PENDING_TIMEOUT_MINUTES = ${REVIEW_PENDING_TIMEOUT_MINUTES};

// ── Helpers ──

function isCodeFile(filePath: string): boolean {
    return CODE_EXTENSIONS.some((ext) => filePath.endsWith(ext));
}

function isInsideDir(filePath: string, dir: string): boolean {
    const resolved = filePath.startsWith('/') ? filePath : resolve(process.cwd(), filePath);
    return resolved.startsWith(dir + '/') || resolved === dir;
}

function hasBlockedCommand(command: string): string | null {
    for (const cmd of BLOCKED_COMMANDS) {
        if (command.includes(cmd)) return cmd;
    }
    return null;
}

function readJsonSafe(filePath: string): any {
    try {
        return JSON.parse(readFileSync(filePath, 'utf-8'));
    } catch {
        return null;
    }
}

function minutesSince(isoDate: string): number {
    const then = new Date(isoDate).getTime();
    if (isNaN(then)) return 0;
    return Math.floor((Date.now() - then) / 60000);
}

export default {
    name: 'harmonia',
    hooks: {
        // ── Soft boundary interception ──
        'tool.execute.before': async (
            input: { tool: string; sessionID: string; callID: string },
            output: { args: Record<string, any> },
        ) => {
            const toolName = input.tool;
            const args = output.args;

            // Guard 1: Write/Edit tools — check file path
            if (['Write', 'Edit', 'MultiEdit', 'write', 'edit'].includes(toolName)) {
                const filePath = args.file_path || args.filePath || args.path || '';
                if (filePath) {
                    // Allow writes to Harmonia data directory
                    if (isInsideDir(filePath, DATA_DIR)) {
                        return;
                    }

                    // Block writes to code files inside project directory
                    if (isInsideDir(filePath, PROJECT_DIR) && isCodeFile(filePath)) {
                        // Neutralize: replace content with warning, keep path for visibility
                        output.args = {
                            ...args,
                            content: \`[HARMONIA 拦截] PM 不应直接修改代码文件。请通过 dispatch_role 将编码任务分配给 developer。\\n原目标文件: \${filePath}\`,
                            oldString: '__HARMONIA_BLOCKED_EDIT__',
                            newString: '__HARMONIA_BLOCKED_EDIT__',
                        };
                        return;
                    }

                    // Block writes outside both project dir and data dir
                    if (!isInsideDir(filePath, PROJECT_DIR) && !isInsideDir(filePath, DATA_DIR)) {
                        output.args = {
                            ...args,
                            content: \`[HARMONIA 拦截] PM 不应在项目目录和 Harmonia 数据目录之外写文件。请使用 write_doc 工具。\\n原目标路径: \${filePath}\`,
                            oldString: '__HARMONIA_BLOCKED_EDIT__',
                            newString: '__HARMONIA_BLOCKED_EDIT__',
                        };
                        return;
                    }
                }
            }

            // Guard 2: Bash/Terminal — check for dev commands
            if (['Bash', 'bash', 'Terminal', 'terminal'].includes(toolName)) {
                const command = args.command || args.cmd || '';
                if (command) {
                    const blocked = hasBlockedCommand(command);
                    if (blocked) {
                        // Neutralize: replace command with echo warning
                        output.args = {
                            ...args,
                            command: \`echo "[HARMONIA 拦截] PM 不应直接执行开发命令 (\${blocked}...)。请通过 dispatch_role 将任务分配给相应角色（developer/tester）。"\`,
                            cmd: \`echo "[HARMONIA 拦截] PM 不应直接执行开发命令 (\${blocked}...)。请通过 dispatch_role 将任务分配给相应角色（developer/tester）。"\`,
                        };
                        return;
                    }
                }
            }
        },

        // ── Proactive reminders ──
        'experimental.chat.messages.transform': async (
            messages: Array<{ role: string; content: any }>,
        ) => {
            const reminders: string[] = [];

            // Check 1: Running dispatch timeout
            const dispatches = readJsonSafe(resolve(PROJECT_DATA, 'dispatches.json'));
            if (dispatches && Array.isArray(dispatches)) {
                for (const d of dispatches) {
                    if ((d.status === 'running' || d.status === 'dispatched') && d.updatedAt) {
                        const elapsed = minutesSince(d.updatedAt);
                        if (elapsed >= DISPATCH_TIMEOUT_MINUTES) {
                            reminders.push(
                                \`- dispatch \${d.id} (\${d.role}) 已运行 \${elapsed} 分钟，建议调用 get_project_status 检查进度\`,
                            );
                        }
                    }
                }
            }

            // Check 2: Pending document reviews
            const reviews = readJsonSafe(resolve(PROJECT_DATA, 'reviews.json'));
            if (reviews && typeof reviews === 'object') {
                const pendingDocs: string[] = [];
                for (const [docId, review] of Object.entries<any>(reviews)) {
                    if (review.status === 'pending' && review.submittedAt) {
                        const elapsed = minutesSince(review.submittedAt);
                        if (elapsed >= REVIEW_PENDING_TIMEOUT_MINUTES) {
                            pendingDocs.push(docId);
                        }
                    }
                }
                if (pendingDocs.length > 0) {
                    reminders.push(
                        \`- \${pendingDocs.length} 份文档待审核超过 \${REVIEW_PENDING_TIMEOUT_MINUTES} 分钟: \${pendingDocs.join(', ')} — 请尽快处理（approve_doc / reject_doc）\`,
                    );
                }
            }

            // Check 3: Phase idle check
            const state = readJsonSafe(resolve(PROJECT_DATA, 'state.json'));
            if (state && state.updatedAt && state.currentPhase) {
                const idle = minutesSince(state.updatedAt);
                if (idle >= PHASE_IDLE_TIMEOUT_MINUTES) {
                    reminders.push(
                        \`- 当前阶段 (\${state.currentPhase}) 已空闲 \${idle} 分钟，建议调用 get_project_status 检查项目状态\`,
                    );
                }
            }

            // Inject reminders as a system-like message
            if (reminders.length > 0) {
                messages.push({
                    role: 'user',
                    content: \`<harmonia-reminder>
以下事项需要你的关注：

\${reminders.join('\\n')}

请根据提醒采取相应行动。
</harmonia-reminder>\`,
                });
            }

            return messages;
        },
    },
} satisfies Plugin;
`;
}

/**
 * Create OpenCode hook definitions using agent-kit's defineHooks.
 *
 * Produces a single plugin file with both tool.execute.before and
 * experimental.chat.messages.transform hooks.
 */
export function createOpenCodeHooks(params: HookParams) {
    return defineHooks('opencode', {
        events: ['tool.execute.before', 'experimental.chat.messages.transform'],
        content: generateOpenCodePlugin(params),
    });
}
