/**
 * OpenCode hook definitions.
 *
 * OpenCode hooks are TypeScript plugins installed to ~/.config/opencode/plugins/.
 * They export a Plugin object with hooks keyed by event name.
 *
 * Limitations vs Claude Code:
 * - `tool.execute.before` can modify args but CANNOT block tool calls.
 * - No true blocking mechanism (permission.ask is too coarse).
 *
 * Strategy: "soft interception + reminder injection"
 * 1. tool.execute.before — detect boundary violations, replace args to neutralize
 *    the operation (e.g., prepend echo to bash commands, empty write content)
 *    and inject a warning message.
 * 2. experimental.chat.messages.transform — read Harmonia data files, inject
 *    reminders about dispatch timeouts, idle timeouts, pending reviews.
 *
 * Project-agnostic: no project name/dir baked in.
 * - Boundary guard uses tool names + code file extensions only
 * - Reminders scan all projects under DATA_DIR
 */

import { defineHooks } from '@s_s/agent-kit';
import type { HookParams } from './content.js';
import {
    BLOCKED_COMMANDS,
    CODE_EXTENSIONS,
    DISPATCH_TIMEOUT_MINUTES,
    WORKFLOW_IDLE_TIMEOUT_MINUTES,
    REVIEW_PENDING_TIMEOUT_MINUTES,
} from './content.js';

/**
 * Generate the OpenCode plugin TypeScript source code.
 *
 * This produces a single plugin file that handles both:
 * - tool.execute.before: soft boundary interception
 * - experimental.chat.messages.transform: proactive reminders
 */
function generateOpenCodePlugin(params: HookParams): string {
    const codeExtsJson = JSON.stringify(CODE_EXTENSIONS);
    const blockedCmdsJson = JSON.stringify(BLOCKED_COMMANDS);

    // We generate raw TS source as a string. All values from params/constants
    // are baked in as literals at generation time.
    return `import type { Plugin } from 'opencode';
import { readFileSync, readdirSync, statSync } from 'fs';
import { resolve, join } from 'path';

// ── Baked-in constants (generated by Harmonia setup) ──
const DATA_DIR = ${JSON.stringify(params.dataDir)};

const CODE_EXTENSIONS: readonly string[] = ${codeExtsJson};
const BLOCKED_COMMANDS: readonly string[] = ${blockedCmdsJson};
const DISPATCH_TIMEOUT_MINUTES = ${DISPATCH_TIMEOUT_MINUTES};
const WORKFLOW_IDLE_TIMEOUT_MINUTES = ${WORKFLOW_IDLE_TIMEOUT_MINUTES};
const REVIEW_PENDING_TIMEOUT_MINUTES = ${REVIEW_PENDING_TIMEOUT_MINUTES};

// ── Helpers ──

function isCodeFile(filePath: string): boolean {
    return CODE_EXTENSIONS.some((ext) => filePath.endsWith(ext));
}

function hasBlockedCommand(command: string): string | null {
    for (const cmd of BLOCKED_COMMANDS) {
        if (command.includes(cmd)) return cmd;
    }
    return null;
}

function readJsonSafe(filePath: string): any {
    try {
        return JSON.parse(readFileSync(filePath, 'utf-8'));
    } catch {
        return null;
    }
}

function minutesSince(isoDate: string): number {
    const then = new Date(isoDate).getTime();
    if (isNaN(then)) return 0;
    return Math.floor((Date.now() - then) / 60000);
}

/** List project directories under DATA_DIR */
function listProjectDirs(): Array<{ name: string; path: string }> {
    try {
        const entries = readdirSync(DATA_DIR);
        const projects: Array<{ name: string; path: string }> = [];
        for (const entry of entries) {
            const full = join(DATA_DIR, entry);
            try {
                if (statSync(full).isDirectory()) {
                    projects.push({ name: entry, path: full });
                }
            } catch {
                // skip inaccessible entries
            }
        }
        return projects;
    } catch {
        return [];
    }
}

export default {
    name: 'harmonia',
    hooks: {
        // ── Soft boundary interception ──
        'tool.execute.before': async (
            input: { tool: string; sessionID: string; callID: string },
            output: { args: Record<string, any> },
        ) => {
            const toolName = input.tool;
            const args = output.args;

            // Guard 1: Write/Edit tools — check file extension
            if (['Write', 'Edit', 'MultiEdit', 'write', 'edit'].includes(toolName)) {
                const filePath = args.file_path || args.filePath || args.path || '';
                if (filePath && isCodeFile(filePath)) {
                    // Neutralize: replace content with warning
                    output.args = {
                        ...args,
                        content: \`[HARMONIA 拦截] Coordinator 不应直接修改代码文件。请通过 role_dispatch 将编码任务分配给 developer。\\n原目标文件: \${filePath}\`,
                        oldString: '__HARMONIA_BLOCKED_EDIT__',
                        newString: '__HARMONIA_BLOCKED_EDIT__',
                    };
                    return;
                }
            }

            // Guard 2: Bash/Terminal — check for dev commands
            if (['Bash', 'bash', 'Terminal', 'terminal'].includes(toolName)) {
                const command = args.command || args.cmd || '';
                if (command) {
                    const blocked = hasBlockedCommand(command);
                    if (blocked) {
                        output.args = {
                            ...args,
                            command: \`echo "[HARMONIA 拦截] Coordinator 不应直接执行开发命令 (\${blocked}...)。请通过 role_dispatch 将任务分配给相应角色（developer/tester）。"\`,
                            cmd: \`echo "[HARMONIA 拦截] Coordinator 不应直接执行开发命令 (\${blocked}...)。请通过 role_dispatch 将任务分配给相应角色（developer/tester）。"\`,
                        };
                        return;
                    }
                }
            }
        },

        // ── Proactive reminders ──
        'experimental.chat.messages.transform': async (
            messages: Array<{ role: string; content: any }>,
        ) => {
            const reminders: string[] = [];
            const projects = listProjectDirs();

            for (const proj of projects) {
                // Check 1: Running dispatch timeout
                const dispatches = readJsonSafe(resolve(proj.path, 'dispatches.json'));
                if (dispatches && Array.isArray(dispatches)) {
                    for (const d of dispatches) {
                        if ((d.status === 'running' || d.status === 'dispatched') && d.updatedAt) {
                            const elapsed = minutesSince(d.updatedAt);
                            if (elapsed >= DISPATCH_TIMEOUT_MINUTES) {
                                reminders.push(
                                    \`- [\${proj.name}] dispatch \${d.id} (\${d.role}) 已运行 \${elapsed} 分钟，建议调用 project_status 检查进度\`,
                                );
                            }
                        }
                    }
                }

                // Check 2: Pending artifact reviews
                const reviews = readJsonSafe(resolve(proj.path, 'reviews.json'));
                if (reviews && typeof reviews === 'object') {
                    const pendingArtifacts: string[] = [];
                    for (const [artifactId, review] of Object.entries<any>(reviews)) {
                        if (review.status === 'pending' && review.submittedAt) {
                            const elapsed = minutesSince(review.submittedAt);
                            if (elapsed >= REVIEW_PENDING_TIMEOUT_MINUTES) {
                                pendingArtifacts.push(artifactId);
                            }
                        }
                    }
                    if (pendingArtifacts.length > 0) {
                        reminders.push(
                            \`- [\${proj.name}] \${pendingArtifacts.length} 份制品待审核超过 \${REVIEW_PENDING_TIMEOUT_MINUTES} 分钟: \${pendingArtifacts.join(', ')} — 请尽快处理（artifact_approve）\`,
                        );
                    }
                }

                // Check 3: Workflow idle check
                const state = readJsonSafe(resolve(proj.path, 'state.json'));
                if (state && state.updatedAt) {
                    const idle = minutesSince(state.updatedAt);
                    if (idle >= WORKFLOW_IDLE_TIMEOUT_MINUTES) {
                        reminders.push(
                            \`- [\${proj.name}] 工作流已空闲 \${idle} 分钟，建议调用 project_status 检查项目状态\`,
                        );
                    }
                }
            }

            // Inject reminders as a system-like message
            if (reminders.length > 0) {
                messages.push({
                    role: 'user',
                    content: \`<harmonia-reminder>
以下事项需要你的关注：

\${reminders.join('\\n')}

请根据提醒采取相应行动。
</harmonia-reminder>\`,
                });
            }

            return messages;
        },
    },
} satisfies Plugin;
`;
}

/**
 * Create OpenCode hook definitions using agent-kit's defineHooks.
 *
 * Produces a single plugin file with both tool.execute.before and
 * experimental.chat.messages.transform hooks.
 */
export function createOpenCodeHooks(params: HookParams) {
    return defineHooks('opencode', {
        events: ['tool.execute.before', 'experimental.chat.messages.transform'],
        content: generateOpenCodePlugin(params),
    });
}
